import About from '@/components/About'
import Contact from '@/components/Contact'
import Footer from '@/components/Footer'
import Hero from '@/components/Hero'
import Navbar from '@/components/Navbar'
import Project from '@/components/Project'
import Skills from '@/components/Skills'
import Head from 'next/head'



export default function Home() {
  return (
    <>  
      <Head>
        <title>Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-full h-screen text-white bg-[#060918] overflow-x-hidden overflw-y-scroll '>
        <Navbar/>
        <Hero/>
        <About/>
        <Skills/>
        <Project/>
        <Contact/>
        <Footer/>
      </main>
      
    </>
  )
}
